### ISSUE TITLE
Cosa facciamo

### ISSUE THREAD

**Issue by nicolabruno** [factcheckersit/website#4]
Allineare al centro i box

**Comment by nelsonmau** [comment]
fatto, la procedura è facile.

* prima ciascun item del portfolio era all'interno di questo div `<div class="col-sm-4 portfolio-item">`
* ora invece ho cambiato la classe e il div è così `<div class="col-sm-6 portfolio-item">`

in pratica dove c'era il 4 ho messo il 6.
questo perché Bootstrap (che è il framework con cui è fatto il template del sito) ha introdotto uno standard: le pagine vengono divise in dodici colonne e così, puoi assegnare ad ogni oggetto un numero di colonne tale da farglielo impaginare come vuoi tu. Ad esempio:

* mettere due oggetto con 6 colonne ciascuno (come ho fatto ora io) signifa assegnare a entrambi la metà dello spazio.
* mettere un solo oggetto largo 12 colonne, significa che occuperà il totale dello spazio.

tutto questo si fa semplicemente assegnando una classe all'oggetto (può essere un `<div>` o un `<p>`) che è questa class="col-sm-6" dove

col = colonne
6 = numero di colonne assegnate all'oggetto
sm = formato del device (quest'ultimo è strafigo perché ci fai i siti responsibivi. sm = small device, lg = large device, xs = mobile...)

i docs sono qui https://getbootstrap.com/examples/grid/

**Comment by nelsonmau** [comment]
fixed https://github.com/factcheckersit/website/commit/48c2ba95962109f7ec531645dbc7340642d96f9e

**Comment by nicolabruno** [comment]
Ok grazie, utili i docs
Invece per allinearli in verticale (cioè avere la stessa distanza tra un box e l'altro sia in verticale che in orizzontale?)

Altra cosa: ora abbiamo messo noi i titoli dei box, ma non mi convince molto. si potrebbe invece farli comparire in mouseover?
