### ISSUE TITLE
Configurare contact form

### ISSUE THREAD

**Issue by nicolabruno** [factcheckersit/website#6]

**Comment by nicolabruno** [comment]
@jenkin riesci a darci una mano su questo? vorremmo andare online asap ;-)

**Comment by jenkin** [comment]
Volentieri, ma ho bisogno di due informazioni:

* su che server deve girare lo script https://github.com/factcheckersit/website/blob/master/mail/contact_me.php
* che mail server devo usare per mandare le mail?

**Comment by nicolabruno** [comment]
grazie @jenkin

**Comment by nicolabruno** [comment]
scusa @jenkin 

la mail è 
factcheckers.it@gmail.com

server è qui 
ftp: factcheckers.ensoul.works

**Comment by jenkin** [comment]
Dunque, se vuoi inviare le mail da form di contatto mediante quell'account google, bisogna cambiare lo script php in qualcosa del genere: http://stackoverflow.com/a/12317831.

Ma il sito alla fine sarà ospitato in un hosting di questa azienda: https://ensoul.it/. Quando lo hai comprato nel pacchetto c'è anche la mail @factcheckers.it? Perché se è così, il problema è già risolto e tutto funzionerà appena carichi questo repository sui loro server...

**Comment by nicolabruno** [comment]
Il server è di uno dei soci dell'associazione
Non abbiamo email @factcheckers.it, preferiamo usare gmail

Ok per lo script php da inserire!
