### ISSUE TITLE
Mettere sito online

### ISSUE THREAD

**Issue by nicolabruno** [factcheckersit/website#7]
Vi mando indicazioni hosting via email

**Comment by jenkin** [comment]
Deploy completato: https://factcheckers.it/. Il vecchio sito in wordpress è ancora attivo all'indirizzo https://factcheckers.it/wp/ (sono saltate giusto un paio di immagini). Ovviamente qualsiasi modifica a questo repository richiede un nuovo deploy (scarica lo zip, decomprimi, carica sul server, sostituisci tutto).

**Comment by nelsonmau** [comment]
@jenkin perché tutto sto popò per deployare? non si può fare git pull da ssh?

**Comment by jenkin** [comment]
No, il server dell'amico di @nicolabruno non permette accesso ssh, solo da sftp, quindi tutto a manina... ;)
