### ISSUE TITLE
Sezione Network

### ISSUE THREAD

**Issue by nicolabruno** [factcheckersit/website#8]
- Link da menù a sezione è rotto

- dovremmo inserire i loghi delle 4 università in elenco. I loghi sono già caricati

**Comment by nelsonmau** [comment]
ora il link funziona

occhio però, tutta la parte 'network' ha una grafica fai da te e rischia di diventare bruttina...

come vuoi mettere i loghi? hai un'idea della posizione?
ricorda sempre che possiamo facilmente usare il meccanismo delle colonne
